### PR TITLE
add citation file #151

### LINKED ISSUE #151: Provide a CITATION.cff for FMI4cpp
Dear @markaren 

how should we cite fmi4cpp ? 
I suggest that you use CITATION.cff file in order to add a Cite This Repository  button to fmi4cpp

### PR DESCRIPTION
**Pull request by prudhomm**
please check out https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

that way we can cite your work on fmi4cpp and Github adds a nice `Cite this repository` button  :)

- closes #151

### CODE REVIEW

**Comment by prudhomm** [comment]
by the way @markaren if you push fmi4cpp to Zenodo you then get a DOI that you can add to the citation file
check it out here https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

it is really nice to get your work easily citeable

**Comment by markaren** [comment]
I'll look into it. Are you in a hurry with publishing a paper that should include a reference?

**Comment by prudhomm** [comment]
yes we are :) we have to submit the paper end of october

**Comment by prudhomm** [comment]
the CFF file is sufficient to get a nice bibtex from Github. The doi is of course better and the publisher asks that we have DOIs associated with our references. We won't be able to have that all the publications we cite, so it is not a biggy. 
Would be nice though, in the future ;)

**Pull request merged**
