### PR TITLE
add dll folder as loading library search path

### PR DESCRIPTION
**Pull request by WeilongWen**

### CODE REVIEW

**Comment by markaren** [comment]
Just to make sure I got this right:

On Windows, this PR adds the directory of the dll to be loaded to PATH (or akin to it), so that dependent DLLs can be loaded?
Sounds reasonable. How about `RemoveDllDirectory`, does the directory not need to be searchable for the duration of the dll usage?

**Comment by markaren** [comment]
But what if the dependent dlls are loaded dynamically in the first dll? Iassume that would cause issues. I supppose a more eloborate solution would be to keep the searchpath as long as the FMU is used.

Whith that said, I do suppose this resolved one class of issues.

**Comment by WeilongWen** [comment]
You are right.  I'm ignoring that dlls that are being dependent on May also be loaded dynamically.  We can keep the search path until the fmu is released.

**Comment by markaren** [comment]
I'm merging this as is, as it solves an issue. Keeping the path for a longer duration can be a possible future enhancement.

**Comment by WeilongWen** [comment]
In the near future, I will do this.

**Pull request merged**
